[env:esp32-s3-eth]
platform = espressif32
board = esp32-s3-devkitc-1-16mb
framework = arduino

upload_speed = 921600
monitor_speed = 115200
monitor_eol = LF
monitor_filters = send_on_enter

board_build.usb_cdc_on_boot = 1
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.filesystem = littlefs
board_build.partitions = partitions/control_16MB.csv

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DARDUINOJSON_ENABLE_COMMENTS=1
    -include src/glibcxx_fix.h

extra_scripts = 
    pre:scripts/make_web_file_hedder.py
    pre:scripts/cc_env.py

lib_deps = 
    olikraus/U8g2 @ ^2.36.15
    bblanchon/ArduinoJson @ ^7.0.4
    arduino-libraries/Ethernet @ ^2.0.2
    arduino-libraries/ArduinoHttpClient @ ^0.6.1
    mobizt/ESP_SSLClient @ ^3.1.3
