#pragma once

#include <stddef.h>
#include <stdint.h>

// Auto-generated by scripts/make_web_file_hedder.py. Do not edit manually.
// Symbols emitted by PlatformIO/ESP-IDF for embedded web files.
extern const uint8_t web_config_html_start[] asm("_binary_web_config_html_start");
extern const uint8_t web_config_html_end[] asm("_binary_web_config_html_end");
extern const uint8_t web_config_html_size[] asm("_binary_web_config_html_size");

extern const uint8_t web_favicon_ico_start[] asm("_binary_web_favicon_ico_start");
extern const uint8_t web_favicon_ico_end[] asm("_binary_web_favicon_ico_end");
extern const uint8_t web_favicon_ico_size[] asm("_binary_web_favicon_ico_size");

extern const uint8_t web_index_html_start[] asm("_binary_web_index_html_start");
extern const uint8_t web_index_html_end[] asm("_binary_web_index_html_end");
extern const uint8_t web_index_html_size[] asm("_binary_web_index_html_size");

extern const uint8_t web_tanks_html_start[] asm("_binary_web_tanks_html_start");
extern const uint8_t web_tanks_html_end[] asm("_binary_web_tanks_html_end");
extern const uint8_t web_tanks_html_size[] asm("_binary_web_tanks_html_size");

struct EmbeddedWebFile
{
	const char *path;
	const uint8_t *start;
	const uint8_t *end;
	const uint8_t *size;
	const char *content_type;
	bool gzip;
};

static const EmbeddedWebFile WEB_FILES[] = {
	{"/config.html", web_config_html_start, web_config_html_end, web_config_html_size, "text/html", false},
	{"/favicon.ico", web_favicon_ico_start, web_favicon_ico_end, web_favicon_ico_size, "image/x-icon", false},
	{"/", web_index_html_start, web_index_html_end, web_index_html_size, "text/html", false},
	{"/index.html", web_index_html_start, web_index_html_end, web_index_html_size, "text/html", false},
	{"/tanks.html", web_tanks_html_start, web_tanks_html_end, web_tanks_html_size, "text/html", false},
};

static const int WEB_INDEX_PAGE_INDEX = 2;

static const size_t WEB_FILES_COUNT = sizeof(WEB_FILES) / sizeof(WEB_FILES[0]);
