from pathlib import Path
import mimetypes
import re


try:
	Import("env")
except NameError:
	env = None


TEXT_EXTENSIONS = {
	".css",
	".csv",
	".html",
	".htm",
	".js",
	".json",
	".md",
	".mjs",
	".svg",
	".txt",
	".xml",
}

CONTENT_TYPE_OVERRIDES = {
	".css": "text/css",
	".html": "text/html",
	".htm": "text/html",
	".ico": "image/x-icon",
	".js": "application/javascript",
	".json": "application/json",
	".svg": "image/svg+xml",
}


def _sanitize_symbol_name(path: str) -> str:
	# Match ESP-IDF generated symbol naming for embedded resources.
	return re.sub(r"[^0-9a-zA-Z]", "_", path)


def _content_type_for(route_path: str) -> str:
	base_route = route_path[:-3] if route_path.endswith(".gz") else route_path
	suffix = Path(base_route).suffix.lower()
	if suffix in CONTENT_TYPE_OVERRIDES:
		return CONTENT_TYPE_OVERRIDES[suffix]

	guessed = mimetypes.guess_type(base_route, strict=False)[0]
	if guessed:
		return guessed

	return "application/octet-stream"


def _route_for(rel_path: str) -> tuple[str, bool]:
	route = f"/{rel_path}"
	gzip = False
	if route.endswith(".gz"):
		route = route[:-3]
		gzip = True
	return route, gzip


def _generate_header(project_dir: Path, web_files: list[Path]) -> None:
	header_path = project_dir / "lib" / "4_web_server" / "web_files.h"
	lines: list[str] = [
		"#pragma once",
		"",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"",
		"// Auto-generated by scripts/make_web_file_hedder.py. Do not edit manually.",
		"// Symbols emitted by PlatformIO/ESP-IDF for embedded web files.",
	]

	entries: list[dict[str, str | bool]] = []
	for file_path in web_files:
		rel_path = file_path.relative_to(project_dir).as_posix()
		web_rel = file_path.relative_to(project_dir / "web").as_posix()
		symbol_core = _sanitize_symbol_name(rel_path)
		var_name = symbol_core
		route, gzip = _route_for(web_rel)
		content_type = _content_type_for(route)

		lines.append(
			f'extern const uint8_t {var_name}_start[] asm("_binary_{symbol_core}_start");'
		)
		lines.append(
			f'extern const uint8_t {var_name}_end[] asm("_binary_{symbol_core}_end");'
		)
		lines.append(
			f'extern const uint8_t {var_name}_size[] asm("_binary_{symbol_core}_size");'
		)
		lines.append("")

		entries.append(
			{
				"route": route,
				"var_name": var_name,
				"content_type": content_type,
				"gzip": gzip,
			}
		)

	lines.extend(
		[
			"struct EmbeddedWebFile",
			"{",
			"\tconst char *path;",
			"\tconst uint8_t *start;",
			"\tconst uint8_t *end;",
			"\tconst uint8_t *size;",
			"\tconst char *content_type;",
			"\tbool gzip;",
			"};",
			"",
			"static const EmbeddedWebFile WEB_FILES[] = {",
		]
	)

	web_index_page_index = -1
	generated_index = 0

	for entry in entries:
		route = entry["route"]
		var_name = entry["var_name"]
		content_type = entry["content_type"]
		gzip = "true" if entry["gzip"] else "false"

		if route == "/index.html":
			if web_index_page_index == -1:
				web_index_page_index = generated_index
			lines.append(
				f'\t{{"/", {var_name}_start, {var_name}_end, {var_name}_size, "{content_type}", {gzip}}},'
			)
			generated_index += 1

		lines.append(
			f'\t{{"{route}", {var_name}_start, {var_name}_end, {var_name}_size, "{content_type}", {gzip}}},'
		)
		generated_index += 1

	lines.extend(
		[
			"};",
			"",
			f"static const int WEB_INDEX_PAGE_INDEX = {web_index_page_index};",
			"",
			"static const size_t WEB_FILES_COUNT = sizeof(WEB_FILES) / sizeof(WEB_FILES[0]);",
		]
	)

	header_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _configure_embedded_files(web_files: list[Path], project_dir: Path) -> tuple[list[str], list[str]]:
	embed_txtfiles: list[str] = []
	embed_files: list[str] = []

	for file_path in web_files:
		rel_path = file_path.relative_to(project_dir).as_posix()
		suffix = file_path.suffix.lower()
		if suffix in TEXT_EXTENSIONS and not rel_path.endswith(".gz"):
			embed_txtfiles.append(rel_path)
		else:
			embed_files.append(rel_path)

	return embed_txtfiles, embed_files


def main() -> None:
	project_dir = (
		Path(env.subst("$PROJECT_DIR")) if env is not None else Path(__file__).resolve().parents[1]
	)
	web_dir = project_dir / "web"
	web_files = sorted([path for path in web_dir.glob("**/*") if path.is_file()])

	_generate_header(project_dir, web_files)

	if env is not None:
		embed_txtfiles, embed_files = _configure_embedded_files(web_files, project_dir)
		cppdefines = []
		if embed_txtfiles:
			cppdefines.append(("COMPONENT_EMBED_TXTFILES", ":".join(embed_txtfiles)))
		if embed_files:
			cppdefines.append(("COMPONENT_EMBED_FILES", ":".join(embed_files)))

		if cppdefines:
			env.AppendUnique(CPPDEFINES=cppdefines)


main()